### ISSUE TITLE
Read-only wiki?

### ISSUE THREAD

**Issue by justinclift** [dilshan/usb2-power-hub#2]
Just went to adjust some pieces in the wiki (mainly to add an overall "[Wiki History](https://github.com/dilshan/usb2-power-hub/wiki/_history)" link), but it's read only. :frowning: 

Would it be ok to make it open to anyone on GitHub for editing?

**Comment by dilshan** [comment]
Hi  justinclift, It seems in GitHub wikis are locked in default settings. :O 

I update the settings and now wikis are open for everyone.

**Comment by justinclift** [comment]
Yeah, it's yet another change in defaults from open -> not open, but not broadly announced by GitHub. :frowning:

Thanks for fixing it. :smile:
